// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8u8YqdtJmoY9j-gAxjnICmTVUMdGbLYw',
    appId: '1:1017739853482:web:082a954ab7945a53b75ad3',
    messagingSenderId: '1017739853482',
    projectId: 'flutter-chat-ebd2e',
    authDomain: 'flutter-chat-ebd2e.firebaseapp.com',
    storageBucket: 'flutter-chat-ebd2e.appspot.com',
    measurementId: 'G-8RGKXWNVFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpUyUMXcNjc7ySGzkIQLkhUB5_ATPvZuE',
    appId: '1:1017739853482:android:7c7c6e8426469a01b75ad3',
    messagingSenderId: '1017739853482',
    projectId: 'flutter-chat-ebd2e',
    storageBucket: 'flutter-chat-ebd2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRfIdlLlkF2-8HgsZW3M3gKRnin2zmCEo',
    appId: '1:1017739853482:ios:dc7d087545a21ae4b75ad3',
    messagingSenderId: '1017739853482',
    projectId: 'flutter-chat-ebd2e',
    storageBucket: 'flutter-chat-ebd2e.appspot.com',
    iosClientId: '1017739853482-fi60ls5ind9skdq5kc8b67u39r429g8e.apps.googleusercontent.com',
    iosBundleId: 'com.chatapp.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRfIdlLlkF2-8HgsZW3M3gKRnin2zmCEo',
    appId: '1:1017739853482:ios:dc7d087545a21ae4b75ad3',
    messagingSenderId: '1017739853482',
    projectId: 'flutter-chat-ebd2e',
    storageBucket: 'flutter-chat-ebd2e.appspot.com',
    iosClientId: '1017739853482-fi60ls5ind9skdq5kc8b67u39r429g8e.apps.googleusercontent.com',
    iosBundleId: 'com.chatapp.chatApp',
  );
}
